name: Tormater.com

defaults:
  -
    scope:
      path: ""
    values:
      meta_title: ""
      meta_desc: "Tormater.com is the official homepage of the Tormater community, and it holds a variety of our projects, resources and information."
      meta_img: "assets/images/forum.png"
  -
    scope:
      path: "wiki/tormater-forum"
    values:
      layout: "wiki"
      wiki_name: Tormater Forum Wiki
      wiki_path: "/wiki/tormater-forum/"
